<?php 
define("MAX_LOGIN_SIZE", 50);
define("MIN_LOGIN_SIZE", 6);
define("MAX_PASSWORD_SIZE", 20);
define("MIN_PASSWORD_SIZE", MAX_PASSWORD_SIZE);
define("MAX_DESCRIPTION_SIZE", 100);
define("MIN_DESCRIPTION_SIZE", 0);
define("MAX_LOCATION_SIZE", 50);
define("MIN_LOCATION_SIZE", 2);
define("MAX_FIRSTNAME_SIZE", 20);
define("MIN_FIRSTNAME_SIZE", 0);
define("MAX_LASTNAME_SIZE", MAX_FIRSTNAME_SIZE);
define("MIN_LASTNAME_SIZE", 0);
define("MAX_EMAIL_SIZE", MAX_LOGIN_SIZE);
define("MIN_EMAIL_SIZE", MIN_LOGIN_SIZE);

?>